-- Wojciech Adamiec, grupa mpy
-- Zadanie 1

SELECT COUNTRY.NAME,
	COUNT(DISTINCT ISLANDIN.ISLAND)
FROM COUNTRY
LEFT JOIN GEO_SEA ON COUNTRY.CODE = GEO_SEA.COUNTRY
LEFT JOIN ISLANDIN ON GEO_SEA.SEA = ISLANDIN.SEA
GROUP BY COUNTRY.CODE
ORDER BY COUNT DESC;

-- Zadanie 2

SELECT COUNTRY.NAME,
	AUX.PERCENTAGE
FROM
				(SELECT DISTINCT ETHNICGROUP.COUNTRY,
						ETHNICGROUP.PERCENTAGE
					FROM ETHNICGROUP
					WHERE ETHNICGROUP.NAME = 'Polish')AUX
JOIN COUNTRY ON COUNTRY.CODE = AUX.COUNTRY
JOIN ETHNICGROUP ON COUNTRY.CODE = ETHNICGROUP.COUNTRY
GROUP BY COUNTRY.NAME,
	AUX.PERCENTAGE
HAVING COUNT(*) > 9;

-- Zadanie 3

-- Zadanie 4

SELECT COUNTRY.NAME,
	CAST(SUM(CITY.POPULATION) / COUNTRY.POPULATION * 100 AS integer) AS PROCENT
FROM COUNTRY
JOIN CITY ON COUNTRY.CODE = CITY.COUNTRY
GROUP BY COUNTRY.CODE
HAVING SUM(CITY.POPULATION) > 0
AND SUM(CITY.POPULATION) / COUNTRY.POPULATION >= 0.75
ORDER BY PROCENT DESC;