-- Wojciech Adamiec, grupa mpy
-- Zadanie 1

CREATE VIEW SEAAIRPORTS(IATACODE,
NAME,
CITY,
PROVINCE,
COUNTRY,
SEA) AS
SELECT AIRPORT.IATACODE,
	AIRPORT.NAME,
	AIRPORT.CITY,
	AIRPORT.PROVINCE,
	AIRPORT.COUNTRY,
	LOCATED.SEA
FROM AIRPORT
JOIN CITY ON CITY.NAME = AIRPORT.CITY
AND CITY.COUNTRY = AIRPORT.COUNTRY
AND CITY.PROVINCE = AIRPORT.PROVINCE
JOIN LOCATED ON CITY.NAME = LOCATED.CITY
AND CITY.COUNTRY = LOCATED.COUNTRY
AND CITY.PROVINCE = LOCATED.PROVINCE
WHERE SEA IS NOT NULL
				AND CITY.ELEVATION > 200;

-- Zadanie 2

-- Zadanie 3

INSERT INTO COUNTRYPOPS(COUNTRY,
YEAR,
POPULATION)
SELECT COUNTRY.CODE,
	EXTRACT(YEAR
	FROM CURRENT_DATE) AS YEAR,
	COUNTRY.POPULATION
FROM COUNTRY;

-- Zadanie 4

ALTER TABLE COUNTRY ADD COLUMN POPPEAKCOUNT numeric, ADD COLUMN POPPEAKYEAR numeric;

UPDATE COUNTRY
SET POPPEAKCOUNT = AUX.COUNT,
	POPPEAKYEAR = AUX.YEAR
FROM
(WITH MAXIMPOP AS
(SELECT COUNTRY,
	MAX(COUNTRYPOPS.POPULATION) AS COUNT
	FROM COUNTRYPOPS
	GROUP BY COUNTRYPOPS.COUNTRY) SELECT MAXIMPOP.COUNTRY,
	COUNT,
	YEAR
	FROM MAXIMPOP
	JOIN COUNTRYPOPS ON (MAXIMPOP.COUNT = COUNTRYPOPS.POPULATION)) AS AUX
WHERE AUX.COUNTRY = COUNTRY.CODE;