-- Wojciech Adamiec, grupa mpy
-- Zadanie 1

SELECT CITY.*
FROM CITY
JOIN AIRPORT ON CITY.NAME = AIRPORT.CITY
WHERE CITY.ELEVATION < 100
				AND CITY.COUNTRY = 'PL'
ORDER BY CITY.NAME;

-- Zadanie 2

SELECT DISTINCT SEA.NAME,
	SEA.AREA
FROM SEA
JOIN RIVER ON SEA.NAME = RIVER.SEA
JOIN GEO_RIVER ON RIVER.NAME = GEO_RIVER.RIVER
WHERE RIVER.LENGTH > 800
				AND GEO_RIVER.COUNTRY = 'F'
ORDER BY SEA.AREA DESC;
